---
version: "3.9"
services:
  backend:
    image: python:3.8.5
    working_dir: /app
    command: ["./test.sh"]
    volumes:
      - ./dev/backend:/app:delegated
      - ./src/AkvoResponseGrouper:/app/AkvoResponseGrouper:delegated
    environment:
      - DATABASE_URL=postgresql://akvo:password@db:5432/demo
    depends_on:
      - db
    ports:
      - 5000:5000
